name: 'Triage Kubeflow Issues'
description: Triage issues for the kubeflow project.  https://github.com/kubeflow/
author: Hamel Husain
inputs:
  NEEDS_TRIAGE_PROJECT_CARD_ID:
    description: The Project Card ID that you want to move issues to.
    required: true
    default: 'MDEzOlByb2plY3RDb2x1bW41OTM0MzEz'
  ISSUE_NUMBER:
    description: The issue number in the current repo that you want to triage.
    required: true
  GITHUB_PERSONAL_ACCESS_TOKEN:
    description: personal access token that is authorized to modify the project kanban board
    required: true
branding:
  color: 'blue'
  icon: 'check-square'
runs:
  using: 'docker'
  image: 'docker://kubeflow/kubeflow-triage'