
name: Build-Kubeflow-Triage
on: [push]

jobs:
  pre-build-container:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Build Image
        # TODO Update To GCR
        run: |
          cd $GITHUB_WORKSPACE
          echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
          docker build -t kubeflow/kubeflow-triage -f Issue_Triage/Dockerfile .
          docker push kubeflow/kubeflow-triage
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
